### ISSUE TITLE
Beta roadmap

### ISSUE THREAD

**Issue by Niklan** [Niklan/fz152#1]
- [x] Сделать хук с `title`, `page callback` и `form callback` вместо просто запроса массива. Ключ использовать как часть для пути админки и таб добавлять автоматически.
- [x] Сделать модуль `fz152_webform`.
- [x] Сделать модуль `fz152_entityform`.
- [x] Добавить галочку отключения генерации страницы с юридической информацией. Возможно у кого-то это уже есть на отдельных страницах и новая не требуется.
- [x] Вынести настройки для страницы на отдельную вкладку.
- [x] Переделать поле для ввода HTML для галочки на формат ввода большого текста, так как в `textfield` не влазят длинные ссылки, в случае если нужно сослать на файлы с длинным адресом.
- [x] Проверить поведение двух форм на одной странице с этими галочками. Похоже на то, что нажатие на label для одной галочки может отметить чекбокс совершенно другой формы. В таком случае добавлять соль в название чекбокса или название формы, или хотябы первые 6 символов формы, или md5 названия формы, чтобы было короче в некоторых случаях. В общем добавить уникальности чтобы таких косяков не было если воспроизведется.
